#https://github.com/Julian-Nash/docker-flask-nginx-redis-mongo

version: "3.9"
services:

  flask:
    build: ./flask
    container_name: vtracer_flask
    restart: always
    ports:
      - "5678:5678"
    depends_on:
      - redis
      - mongodb
    volumes:
      - "/mnt/vtracer-files/logs/flask:/var/log/flask"
    environment:
      - SSL_CERTIFICATE=$SSL_CERTIFICATE
      - SSL_PRIVATEKEY=$SSL_PRIVATEKEY
      - SERVICE_PORT=5678
      - MONGODB_URL=mongodb://mongodb:27017
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:alpine
    container_name: vtracer_redis
    restart: always

  mongodb:
    image: mongo
    container_name: vtracer_mongo
    restart: always
    volumes:
      - "/var/lib/mongodb:/data/db"
      - "/var/log/mongodb:/var/log/mongodb"

  nginx:
    build: ./nginx
    container_name: vtracer_nginx
    restart: always
    volumes:
      - "/mnt/vtracer-files/logs/nginx:/var/log/nginx"
    environment:
      - SSL_CERTIFICATE=$SSL_CERTIFICATE
      - SSL_PRIVATEKEY=$SSL_PRIVATEKEY