#https://github.com/Julian-Nash/docker-flask-nginx-redis-mongo

version: "3.9"
services:

  redis:
    image: redis:alpine
    container_name: redis
    restart: always

  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - "/var/lib/mongodb:/data/db"
      - "/var/log/mongodb:/var/log/mongodb"
    ports:
      - "27017:27017"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports: "80:80"
    volumes:

  flask:
    build: ./flask
    restart: always
    depends_on:
      - redis
      - mongodb
    environment:
      - SSL_CERTIFICATE=$SSL_CERTIFICATE
      - SSL_PRIVATEKEY=$SSL_PRIVATEKEY