#https://github.com/Julian-Nash/docker-flask-nginx-redis-mongo

version: "3.9"
services:

  flask:
    build: ./flask
    container_name: vtracer_flask
    #restart: always
    depends_on:
      - redis
      - mongodb
    volumes:
      - "/mnt/vtracer-files/logs/flask:/var/log/flask"
    environment:
      - SSL_CERTIFICATE=$SSL_CERTIFICATE
      - SSL_PRIVATEKEY=$SSL_PRIVATEKEY
      - MONGODB_URL=$MONGODB_URL

  redis:
    image: redis:alpine
    container_name: vtracer_redis
    restart: always

  mongodb:
    image: mongo
    container_name: vtracer_mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - "/var/lib/mongodb:/data/db"
      - "/var/log/mongodb:/var/log/mongodb"

  nginx:
    build: ./nginx
    container_name: vtracer_nginx
    restart: always
    volumes:
      - "/mnt/vtracer-files/logs/nginx:/var/log/nginx"